global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-CURdashboard  # This will need to be updated before new repo use
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-2
  reporting: true
tests:
  deploy:
    parameter_input: CURdashboardParams.json
    template_file: CURdashboard-master.template
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-2
